[program:tas-websocket-manager-v2]
process_name=%(program_name)s
command=php /var/www/TelegramApiServerManagement/artisan websocket:manager-v2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/TelegramApiServerManagement/storage/logs/websocket-v2.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=10
stopsignal=TERM

[program:tas-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/TelegramApiServerManagement/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/TelegramApiServerManagement/storage/logs/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=10





